### ISSUE TITLE
Is IPv6 supported

### ISSUE THREAD

**Issue by thanasisk** [mariocandela/beelzebub#103]
Hello there,
I didn't have had a ton of time to read through all the codebase. I was wondering what is the status of IPv6 support?

**Comment by mariocandela** [comment]
Hello @thanasisk,

Beelzebub supports IPv6, execute beelzebub localy using docker and then: `curl -6 "http://[::1]:80/"` or `ssh -6 root@::1`

I'm here if you need anything. 

Thanks for your time 

Cheers 

Mario

**Comment by thanasisk** [comment]
many thanks for the quick reply @mariocandela 
Please allow me to drill down a bit in my question with a couple follow-ups:
In the example above is networking handled by Docker?
I plan to run `Beelzebub` on a dual IP stack cloud instance - I want to expose certain services via IPv4 and others via IPv6
My plan is to compile locally, upload and `chroot` - as opposed to putting stuff inside a container.

**Comment by mariocandela** [comment]
Welcome @thanasisk 

So without docker, you should define ipv4 or ipv6 into your [honeypot service configurations](https://github.com/mariocandela/beelzebub/blob/main/configurations/services/ssh-22.yaml), for example:

Bind on ipv4: `address: ":22"`
Bind on ipv6: `address: "[::1]:22"`

I hope to have helped you. :)

Cheers

Mario

**Comment by thanasisk** [comment]
Awesome, much obliged!
