### ISSUE TITLE
Bug: Inline SSH honeypot command not working 

### ISSUE THREAD

**Issue by mariocandela** [mariocandela/beelzebub#129]
**Describe the bug**
Inline SSH honeypot command not working 

**To Reproduce**
ssh user@host 'ls'

**Expected behavior**
Execute the inline command 

**Additional context**
Thanks @t3chn0m4g3 for reporting the bug

**Comment by t3chn0m4g3** [comment]
@mariocandela Works perfectly fine! Thank you! 🤗 ❤️
