### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by psychomad** [mariocandela/beelzebub#21]
**Describe the bug**
When i try to build main.go i receive this: 
runtime: copying /usr/local/go/src/runtime/asm_amd64.h to /tmp/go-build3666578259/b010/asm_GOARCH.h: write /tmp/go-build3666578259/b010/asm_GOARCH.h: copy_file_range: function not implemented

**Comment by mariocandela** [comment]
Hello @psychomad,

Thanks for your feedback! 

I need more details to analyze your issue, example:  S.O. and arch ? 

Did you try execute Beelzebub using docker ? I suggest docker, you avoid possible configuration problems of your machine.

Thanks for your time! 

cheers 

Mario
